name: CI Pipeline

on:

  push:

    branches:

      - main

jobs:

  rgz:
  
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          
      - name: Install dependencies
        run: |
          pip install bandit  # Установка дополнительных пакетов

      - name: Run security check
        run: |
         bandit -r . -x ./env -x ./venv -x ./.git --exclude ./venv/Lib/site-packages --skip B101,B110,B602,B603,B605,B607  # Проверка безопасности с bandit